import { getWajoKecamatanByKemendagri, getWajoVillageByKemendagriCode } from "./adminMaster.mjs";

// Generated from the current BIG administrative boundaries and GeoJSON datasets.
export const ADMIN_STATS = {
  kabupaten: {
    wajo: {"name": "Wajo", "code": "73.13", "areaHa": 2505.49221043, "metrics": [{"label": "Kecamatan", "value": 14}, {"label": "Desa / Kelurahan", "value": 190}, {"label": "Jenis data terkait", "value": 10}], "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 1049}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 23}, {"layerId": "opd", "label": "Organisasi Perangkat Daerah", "count": 27}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 257}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 58}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 55}, {"layerId": "infra-energi", "label": "Sarana Energi", "count": 8}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 94}, {"layerId": "potensi-pertanian", "label": "Potensi Pertanian", "count": 44}, {"layerId": "potensi-peternakan", "label": "Potensi Peternakan", "count": 21}], "notes": ["Satuan pendidikan: 1.049 data terdaftar; 806 lokasi memiliki koordinat yang dapat dipetakan dan 243 belum dapat ditampilkan sebagai titik."]},
  },
  kecamatan: {
    "sabangparu": {"name": "Sabangparu", "code": "73.13.01", "areaHa": 158.2029814349759, "metrics": [{"label": "Desa / Kelurahan", "value": 15}, {"label": "Jenis data tersedia", "value": 6}], "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 68}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 2}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 16}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 2}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 4}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 8}]},
    "pammana": {"name": "Pammana", "code": "73.13.02", "areaHa": 154.16927694965682, "metrics": [{"label": "Desa / Kelurahan", "value": 16}, {"label": "Jenis data tersedia", "value": 7}], "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 91}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 2}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 15}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 5}, {"layerId": "infra-energi", "label": "Sarana Energi", "count": 4}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 6}]},
    "takkalalla": {"name": "Takkalalla", "code": "73.13.03", "areaHa": 167.3258813402378, "metrics": [{"label": "Desa / Kelurahan", "value": 13}, {"label": "Jenis data tersedia", "value": 7}], "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 56}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 2}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 13}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 5}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 4}, {"layerId": "potensi-pertanian", "label": "Potensi Pertanian", "count": 3}, {"layerId": "potensi-peternakan", "label": "Potensi Peternakan", "count": 2}]},
    "sajoanging": {"name": "Sajoanging", "code": "73.13.04", "areaHa": 173.82418220470996, "metrics": [{"label": "Desa / Kelurahan", "value": 9}, {"label": "Jenis data tersedia", "value": 8}], "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 48}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 2}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 12}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 6}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 1}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 5}, {"layerId": "potensi-pertanian", "label": "Potensi Pertanian", "count": 5}, {"layerId": "potensi-peternakan", "label": "Potensi Peternakan", "count": 1}]},
    "majauleng": {"name": "Majauleng", "code": "73.13.05", "areaHa": 222.0589806403111, "metrics": [{"label": "Desa / Kelurahan", "value": 18}, {"label": "Jenis data tersedia", "value": 7}], "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 92}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 2}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 21}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 5}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 4}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 5}, {"layerId": "potensi-pertanian", "label": "Potensi Pertanian", "count": 4}]},
    "tempe": {"name": "Tempe", "code": "73.13.06", "areaHa": 46.917054323762976, "metrics": [{"label": "Desa / Kelurahan", "value": 16}, {"label": "Jenis data tersedia", "value": 9}], "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 141}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 3}, {"layerId": "opd", "label": "Organisasi Perangkat Daerah", "count": 25}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 34}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 5}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 2}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 11}, {"layerId": "potensi-pertanian", "label": "Potensi Pertanian", "count": 2}, {"layerId": "potensi-peternakan", "label": "Potensi Peternakan", "count": 8}]},
    "belawa": {"name": "Belawa", "code": "73.13.07", "areaHa": 221.32728620564265, "metrics": [{"label": "Desa / Kelurahan", "value": 9}, {"label": "Jenis data tersedia", "value": 7}], "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 100}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 2}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 29}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 5}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 7}, {"layerId": "potensi-pertanian", "label": "Potensi Pertanian", "count": 3}, {"layerId": "potensi-peternakan", "label": "Potensi Peternakan", "count": 2}]},
    "tanasitolo": {"name": "Tanasitolo", "code": "73.13.08", "areaHa": 168.65479719098354, "metrics": [{"label": "Desa / Kelurahan", "value": 19}, {"label": "Jenis data tersedia", "value": 8}], "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 84}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 2}, {"layerId": "opd", "label": "Organisasi Perangkat Daerah", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 15}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 3}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 7}, {"layerId": "potensi-pertanian", "label": "Potensi Pertanian", "count": 6}, {"layerId": "potensi-peternakan", "label": "Potensi Peternakan", "count": 2}]},
    "maniangpajo": {"name": "Maniangpajo", "code": "73.13.09", "areaHa": 196.2427627183007, "metrics": [{"label": "Desa / Kelurahan", "value": 8}, {"label": "Jenis data tersedia", "value": 8}], "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 48}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 10}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 5}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 12}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 8}, {"layerId": "potensi-pertanian", "label": "Potensi Pertanian", "count": 5}, {"layerId": "potensi-peternakan", "label": "Potensi Peternakan", "count": 2}]},
    "pitumpanua": {"name": "Pitumpanua", "code": "73.13.10", "areaHa": 185.14786237156454, "metrics": [{"label": "Desa / Kelurahan", "value": 27}, {"label": "Jenis data tersedia", "value": 10}], "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 109}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 1}, {"layerId": "opd", "label": "Organisasi Perangkat Daerah", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 28}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 7}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 3}, {"layerId": "infra-energi", "label": "Sarana Energi", "count": 1}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 10}, {"layerId": "potensi-pertanian", "label": "Potensi Pertanian", "count": 5}, {"layerId": "potensi-peternakan", "label": "Potensi Peternakan", "count": 4}]},
    "bola": {"name": "Bola", "code": "73.13.11", "areaHa": 178.89472249570002, "metrics": [{"label": "Desa / Kelurahan", "value": 11}, {"label": "Jenis data tersedia", "value": 6}], "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 65}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 16}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 3}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 4}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 7}, {"layerId": "potensi-pertanian", "label": "Potensi Pertanian", "count": 4}]},
    "penrang": {"name": "Penrang", "code": "73.13.12", "areaHa": 138.2975052072029, "metrics": [{"label": "Desa / Kelurahan", "value": 10}, {"label": "Jenis data tersedia", "value": 7}], "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 46}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 11}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 3}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 2}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 5}, {"layerId": "potensi-pertanian", "label": "Potensi Pertanian", "count": 2}]},
    "gilireng": {"name": "Gilireng", "code": "73.13.13", "areaHa": 196.68309112717498, "metrics": [{"label": "Desa / Kelurahan", "value": 9}, {"label": "Jenis data tersedia", "value": 8}], "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 44}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 13}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 4}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 9}, {"layerId": "infra-energi", "label": "Sarana Energi", "count": 1}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 5}, {"layerId": "potensi-pertanian", "label": "Potensi Pertanian", "count": 1}]},
    "keera": {"name": "Keera", "code": "73.13.14", "areaHa": 297.11458452803873, "metrics": [{"label": "Desa / Kelurahan", "value": 10}, {"label": "Jenis data tersedia", "value": 8}], "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 57}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 23}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 4}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 9}, {"layerId": "infra-energi", "label": "Sarana Energi", "count": 1}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 6}, {"layerId": "potensi-pertanian", "label": "Potensi Pertanian", "count": 2}]},
  },
  desa: {
    "takkalalla::leweng": {"name": "Leweng", "kecamatan": "Takkalalla", "code": "73.13.03.2007", "areaHa": 12.789395973968142, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}]},
    "keera::awota": {"name": "Awota", "kecamatan": "Keera", "code": "73.13.14.2002", "areaHa": 51.916312899441955, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 5}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 14}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 1}]},
    "maniangpajo::kalola": {"name": "Kalola", "kecamatan": "Maniangpajo", "code": "73.13.09.2005", "areaHa": 18.424571733398174, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 3}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}]},
    "tanasitolo::inalipue": {"name": "Inalipue", "kecamatan": "Tanasitolo", "code": "73.13.08.2007", "areaHa": 12.574299482056993, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 7}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 4}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 1}]},
    "sabangparu::worongnge": {"name": "Worongnge", "kecamatan": "Sabangparu", "code": "73.13.01.2008", "areaHa": 18.50284271621863, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 2}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}]},
    "pitumpanua::siwa": {"name": "Siwa", "kecamatan": "Pitumpanua", "code": "73.13.10.1002", "areaHa": 7.024096056782534, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 6}, {"layerId": "opd", "label": "Organisasi Perangkat Daerah", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 6}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 2}, {"layerId": "potensi-peternakan", "label": "Potensi Peternakan", "count": 1}]},
    "tanasitolo::pincengpute": {"name": "Pincengpute", "kecamatan": "Tanasitolo", "code": "73.13.08.1003", "areaHa": 6.790659055075036, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 6}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}]},
    "pitumpanua::batu": {"name": "Batu", "kecamatan": "Pitumpanua", "code": "73.13.10.2005", "areaHa": 3.158444499312261, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 4}]},
    "tempe::teddaopu": {"name": "Teddaopu", "kecamatan": "Tempe", "code": "73.13.06.1011", "areaHa": 0.3987726011133416, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 6}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 5}, {"layerId": "potensi-peternakan", "label": "Potensi Peternakan", "count": 1}]},
    "tempe::mattirotappareng": {"name": "Mattiro Tappareng", "kecamatan": "Tempe", "code": "73.13.06.1006", "areaHa": 10.010552452124074, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 7}, {"layerId": "opd", "label": "Organisasi Perangkat Daerah", "count": 1}]},
    "tempe::pattirosompe": {"name": "Pattirosompe", "kecamatan": "Tempe", "code": "73.13.06.1002", "areaHa": 6.22753401996871, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 8}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 2}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 1}, {"layerId": "potensi-peternakan", "label": "Potensi Peternakan", "count": 1}]},
    "sabangparu::bila": {"name": "Bila", "kecamatan": "Sabangparu", "code": "73.13.01.2015", "areaHa": 4.375540234304498, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}]},
    "takkalalla::lamarua": {"name": "Lamarua", "kecamatan": "Takkalalla", "code": "73.13.03.2012", "areaHa": 11.615510831330814, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}]},
    "majauleng::bottotanre": {"name": "Bottotanre", "kecamatan": "Majauleng", "code": "73.13.05.2011", "areaHa": 10.626007248422948, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 4}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}]},
    "pammana::abbanuangnge": {"name": "Abbanuangnge", "kecamatan": "Pammana", "code": "73.13.02.2015", "areaHa": 10.829712903647124, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 3}]},
    "pammana::wecudai": {"name": "Wecudai", "kecamatan": "Pammana", "code": "73.13.02.2009", "areaHa": 7.903648229933962, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 6}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 4}]},
    "majauleng::liu": {"name": "Liu", "kecamatan": "Majauleng", "code": "73.13.05.2015", "areaHa": 6.720195521118108, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 4}]},
    "sajoanging::barangmamase": {"name": "Barangmamase", "kecamatan": "Sajoanging", "code": "73.13.04.2006", "areaHa": 30.286463068464055, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 5}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}]},
    "pitumpanua::alelebbae": {"name": "Ale Lebbae", "kecamatan": "Pitumpanua", "code": "73.13.10.2019", "areaHa": 1.2181562752272137, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 1}]},
    "tempe::lapongkoda": {"name": "Lapongkoda", "kecamatan": "Tempe", "code": "73.13.06.1010", "areaHa": 0.5604800297538844, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 9}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 3}, {"layerId": "potensi-peternakan", "label": "Potensi Peternakan", "count": 1}]},
    "keera::ballaere": {"name": "Ballaere", "kecamatan": "Keera", "code": "73.13.14.1001", "areaHa": 9.169639748553726, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 7}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 3}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 2}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 1}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 1}]},
    "sabangparu::walennae": {"name": "Walennae", "kecamatan": "Sabangparu", "code": "73.13.01.1001", "areaHa": 6.338320138390124, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 2}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}]},
    "pitumpanua::alesilurengnge": {"name": "Alesilurengnge", "kecamatan": "Pitumpanua", "code": "73.13.10.2014", "areaHa": 7.513900598369442, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 2}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 2}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 1}]},
    "tanasitolo::mario": {"name": "Mario", "kecamatan": "Tanasitolo", "code": "73.13.08.2015", "areaHa": 6.465407297647289, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 3}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}]},
    "pitumpanua::lompoloang": {"name": "Lompoloang", "kecamatan": "Pitumpanua", "code": "73.13.10.2008", "areaHa": 12.987914340956076, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 5}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 2}]},
    "bola::lattimu": {"name": "Lattimu", "kecamatan": "Bola", "code": "73.13.11.2009", "areaHa": 18.85292525493406, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 2}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 2}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}]},
    "keera::ciromanie": {"name": "Ciromanie", "kecamatan": "Keera", "code": "73.13.14.2009", "areaHa": 46.44872395137494, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 2}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 3}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 3}]},
    "majauleng::tosora": {"name": "Tosora", "kecamatan": "Majauleng", "code": "73.13.05.2005", "areaHa": 13.39071757013597, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 4}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 6}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 1}]},
    "maniangpajo::abbanuangnge": {"name": "Abbanuangnge", "kecamatan": "Maniangpajo", "code": "73.13.09.2007", "areaHa": 47.424195686753855, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 2}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 10}]},
    "sabangparu::mallusesalo": {"name": "Mallusesalo", "kecamatan": "Sabangparu", "code": "73.13.01.2011", "areaHa": 3.3264881995143036, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 4}]},
    "sabangparu::ugi": {"name": "Ugi", "kecamatan": "Sabangparu", "code": "73.13.01.2005", "areaHa": 4.579175266447678, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 2}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}]},
    "gilireng::poleonro": {"name": "Poleonro", "kecamatan": "Gilireng", "code": "73.13.13.2003", "areaHa": 9.896559258579149, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 3}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}, {"layerId": "infra-energi", "label": "Sarana Energi", "count": 1}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 2}]},
    "sajoanging::alewadeng": {"name": "Alewadeng", "kecamatan": "Sajoanging", "code": "73.13.04.2009", "areaHa": 17.65995380935754, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 5}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 2}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}]},
    "majauleng::tengnga": {"name": "Tengnga", "kecamatan": "Majauleng", "code": "73.13.05.2014", "areaHa": 10.852744831020166, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 5}]},
    "tempe::salomenraleng": {"name": "Salo Menraleng", "kecamatan": "Tempe", "code": "73.13.06.1008", "areaHa": 1.509943666461707, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 2}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}, {"layerId": "potensi-peternakan", "label": "Potensi Peternakan", "count": 1}]},
    "pammana::lampulung": {"name": "Lampulung", "kecamatan": "Pammana", "code": "73.13.02.2010", "areaHa": 7.548599001174167, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 7}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 2}]},
    "sajoanging::akkajeng": {"name": "Akkajeng", "kecamatan": "Sajoanging", "code": "73.13.04.1001", "areaHa": 23.536509077680186, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 7}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 2}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 2}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 3}]},
    "sajoanging::assorajang": {"name": "Assorajang", "kecamatan": "Sajoanging", "code": "73.13.04.1002", "areaHa": 15.336752042664969, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 2}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}]},
    "takkalalla::soro": {"name": "Soro", "kecamatan": "Takkalalla", "code": "73.13.03.2005", "areaHa": 9.454556564416157, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 5}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}]},
    "tempe::sitampae": {"name": "Sitampae", "kecamatan": "Tempe", "code": "73.13.06.1015", "areaHa": 3.909480576309158, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 5}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 1}]},
    "bola::balielo": {"name": "Balielo", "kecamatan": "Bola", "code": "73.13.11.2007", "areaHa": 10.723758997539054, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 4}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 2}]},
    "sabangparu::tadangpalie": {"name": "Tadangpalie", "kecamatan": "Sabangparu", "code": "73.13.01.2013", "areaHa": 9.523045653176506, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 3}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 2}]},
    "bola::ujungtanah": {"name": "Ujungtanah", "kecamatan": "Bola", "code": "73.13.11.2003", "areaHa": 26.422809580486543, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 10}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 2}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 2}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 3}]},
    "tanasitolo::tancung": {"name": "Tancung", "kecamatan": "Tanasitolo", "code": "73.13.08.1001", "areaHa": 16.66107940186682, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 2}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 2}]},
    "pammana::kampiri": {"name": "Kampiri", "kecamatan": "Pammana", "code": "73.13.02.2005", "areaHa": 11.51632692663411, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 6}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 1}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 1}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 1}]},
    "pitumpanua::lauwa": {"name": "Lauwa", "kecamatan": "Pitumpanua", "code": "73.13.10.2006", "areaHa": 10.158628457841791, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 6}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 1}, {"layerId": "potensi-peternakan", "label": "Potensi Peternakan", "count": 1}]},
    "bola::bola": {"name": "Bola", "kecamatan": "Bola", "code": "73.13.11.2002", "areaHa": 16.489328357776234, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 4}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 1}]},
    "tempe::campalagi": {"name": "Campalagi", "kecamatan": "Tempe", "code": "73.13.06.1009", "areaHa": 5.2447495309462235, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 5}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 1}, {"layerId": "opd", "label": "Organisasi Perangkat Daerah", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 9}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 4}]},
    "tanasitolo::lowa": {"name": "Lowa", "kecamatan": "Tanasitolo", "code": "73.13.08.2006", "areaHa": 7.189197724667493, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 2}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 2}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}]},
    "takkalalla::ceppaga": {"name": "Ceppaga", "kecamatan": "Takkalalla", "code": "73.13.03.2006", "areaHa": 14.11005676989496, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 1}, {"layerId": "potensi-peternakan", "label": "Potensi Peternakan", "count": 1}]},
    "tanasitolo::wajoriaja": {"name": "Wajoriaja", "kecamatan": "Tanasitolo", "code": "73.13.08.2009", "areaHa": 11.150070262919346, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 7}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 2}]},
    "takkalalla::bocco": {"name": "Bocco", "kecamatan": "Takkalalla", "code": "73.13.03.1002", "areaHa": 12.55981944074508, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 3}]},
    "pammana::pammana": {"name": "Pammana", "kecamatan": "Pammana", "code": "73.13.02.1001", "areaHa": 11.16567803505696, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 11}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 3}]},
    "belawa::malangke": {"name": "Malangke", "kecamatan": "Belawa", "code": "73.13.07.1002", "areaHa": 12.968862045758227, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 10}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}]},
    "gilireng::lamata": {"name": "Lamata", "kecamatan": "Gilireng", "code": "73.13.13.2005", "areaHa": 25.162460720159313, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 6}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 3}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 1}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 2}]},
    "belawa::sappa": {"name": "Sappa", "kecamatan": "Belawa", "code": "73.13.07.2008", "areaHa": 16.108906249289134, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 10}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 1}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 2}]},
    "pitumpanua::jauhpandang": {"name": "Jauh Pandang", "kecamatan": "Pitumpanua", "code": "73.13.10.2015", "areaHa": 4.775693784441253, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}]},
    "gilireng::paselloreng": {"name": "Paselloreng", "kecamatan": "Gilireng", "code": "73.13.13.2006", "areaHa": 78.79075419451524, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 5}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 1}]},
    "majauleng::bottobenteng": {"name": "Bottobenteng", "kecamatan": "Majauleng", "code": "73.13.05.2010", "areaHa": 17.525311398372928, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 4}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}]},
    "majauleng::bottopenno": {"name": "Bottopenno", "kecamatan": "Majauleng", "code": "73.13.05.2017", "areaHa": 4.184765465422511, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 1}]},
    "penrang::walanga": {"name": "Walanga", "kecamatan": "Penrang", "code": "73.13.12.2007", "areaHa": 10.139218526889804, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 3}]},
    "tanasitolo::palippu": {"name": "Palippu", "kecamatan": "Tanasitolo", "code": "73.13.08.2016", "areaHa": 8.420690422952092, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 4}]},
    "sabangparu::bentenglompoe": {"name": "Benteng Lompoe", "kecamatan": "Sabangparu", "code": "73.13.01.2014", "areaHa": 25.013721729418048, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 6}]},
    "sajoanging::salobulo": {"name": "Salobulo", "kecamatan": "Sajoanging", "code": "73.13.04.2007", "areaHa": 19.367887715223223, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 7}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 5}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 2}]},
    "tanasitolo::tonralipue": {"name": "Tonralipue", "kecamatan": "Tanasitolo", "code": "73.13.08.2017", "areaHa": 23.465555685776334, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 3}, {"layerId": "potensi-peternakan", "label": "Potensi Peternakan", "count": 1}]},
    "penrang::temmabarang": {"name": "Temmabarang", "kecamatan": "Penrang", "code": "73.13.12.2003", "areaHa": 20.315398081147208, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 3}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 2}]},
    "belawa::wele": {"name": "Wele", "kecamatan": "Belawa", "code": "73.13.07.2006", "areaHa": 17.30126715949006, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 11}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}, {"layerId": "potensi-peternakan", "label": "Potensi Peternakan", "count": 1}]},
    "bola::lempong": {"name": "Lempong", "kecamatan": "Bola", "code": "73.13.11.2004", "areaHa": 24.93201123560964, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 6}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 3}]},
    "penrang::doping": {"name": "Doping", "kecamatan": "Penrang", "code": "73.13.12.1001", "areaHa": 16.63803249411961, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 5}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 2}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}]},
    "pitumpanua::benteng": {"name": "Benteng", "kecamatan": "Pitumpanua", "code": "73.13.10.1004", "areaHa": 24.53917780721762, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 6}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 4}]},
    "tempe::laelo": {"name": "Laelo", "kecamatan": "Tempe", "code": "73.13.06.1007", "areaHa": 1.611665834478644, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 4}]},
    "tempe::bulupabbulu": {"name": "Bulu Pabbulu", "kecamatan": "Tempe", "code": "73.13.06.1016", "areaHa": 1.6543012826038992, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 9}, {"layerId": "opd", "label": "Organisasi Perangkat Daerah", "count": 7}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 6}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 2}, {"layerId": "potensi-peternakan", "label": "Potensi Peternakan", "count": 1}]},
    "pitumpanua::baubau": {"name": "Bau-Bau", "kecamatan": "Pitumpanua", "code": "73.13.10.2018", "areaHa": 4.571494240636701, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 3}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 3}]},
    "belawa::limporilau": {"name": "Limporilau", "kecamatan": "Belawa", "code": "73.13.07.2007", "areaHa": 29.952374094016708, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 11}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 5}]},
    "penrang::padaelo": {"name": "Padaelo", "kecamatan": "Penrang", "code": "73.13.12.2002", "areaHa": 23.06485880686515, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 5}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 3}]},
    "tanasitolo::assorajang": {"name": "Assorajang", "kecamatan": "Tanasitolo", "code": "73.13.08.2012", "areaHa": 2.2421623851707495, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 5}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 3}]},
    "tempe::watallipue": {"name": "Watallipue", "kecamatan": "Tempe", "code": "73.13.06.1005", "areaHa": 0.1982170615933846, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 5}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}, {"layerId": "potensi-peternakan", "label": "Potensi Peternakan", "count": 1}]},
    "gilireng::alausalo": {"name": "Alausalo", "kecamatan": "Gilireng", "code": "73.13.13.2007", "areaHa": 9.747802960959042, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 2}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}]},
    "majauleng::watanrumpia": {"name": "Watanrumpia", "kecamatan": "Majauleng", "code": "73.13.05.2018", "areaHa": 5.46049849498921, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 3}]},
    "tanasitolo::waetuwo": {"name": "Wae Tuwo", "kecamatan": "Tanasitolo", "code": "73.13.08.2011", "areaHa": 22.440368091910777, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 5}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}]},
    "pammana::simpursia": {"name": "Simpursia", "kecamatan": "Pammana", "code": "73.13.02.2013", "areaHa": 9.084364612022032, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 6}]},
    "penrang::benteng": {"name": "Benteng", "kecamatan": "Penrang", "code": "73.13.12.2006", "areaHa": 15.441841762053116, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 4}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 2}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 3}]},
    "belawa::belawa": {"name": "Belawa", "kecamatan": "Belawa", "code": "73.13.07.1003", "areaHa": 25.12074027855748, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 7}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 2}]},
    "majauleng::laerung": {"name": "Laerung", "kecamatan": "Majauleng", "code": "73.13.05.2008", "areaHa": 10.935478912231133, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 3}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}]},
    "pitumpanua::maccolliloloe": {"name": "Maccolli Loloe", "kecamatan": "Pitumpanua", "code": "73.13.10.2024", "areaHa": 4.813518787832952, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 1}]},
    "sabangparu::pasaka": {"name": "Pasaka", "kecamatan": "Sabangparu", "code": "73.13.01.2012", "areaHa": 7.080683574691442, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 4}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 1}]},
    "pitumpanua::bottotengnga": {"name": "Botto Tengnga", "kecamatan": "Pitumpanua", "code": "73.13.10.2021", "areaHa": 1.2158534947948427, "status": "Batas Indikatif", "layers": [{"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}]},
    "belawa::lautang": {"name": "Lautang", "kecamatan": "Belawa", "code": "73.13.07.2009", "areaHa": 49.97146537472521, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 7}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 2}]},
    "pitumpanua::tanrongi": {"name": "Tanrongi", "kecamatan": "Pitumpanua", "code": "73.13.10.2007", "areaHa": 9.5206427229309, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 2}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 2}, {"layerId": "potensi-peternakan", "label": "Potensi Peternakan", "count": 1}]},
    "majauleng::limpomajang": {"name": "Limpomajang", "kecamatan": "Majauleng", "code": "73.13.05.1002", "areaHa": 8.52346432052636, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 5}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 2}]},
    "sajoanging::sakkoli": {"name": "Sakkoli", "kecamatan": "Sajoanging", "code": "73.13.04.2005", "areaHa": 28.982166165787962, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 4}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 1}]},
    "sajoanging::towalida": {"name": "Towalida", "kecamatan": "Sajoanging", "code": "73.13.04.2008", "areaHa": 11.499424384427815, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 2}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}, {"layerId": "potensi-peternakan", "label": "Potensi Peternakan", "count": 1}]},
    "takkalalla::manyili": {"name": "Manyili", "kecamatan": "Takkalalla", "code": "73.13.03.2004", "areaHa": 13.754543481105356, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 2}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 1}]},
    "majauleng::uraiyang": {"name": "Uraiyang", "kecamatan": "Majauleng", "code": "73.13.05.1004", "areaHa": 11.479969095385346, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 3}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 1}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 2}]},
    "takkalalla::botto": {"name": "Botto", "kecamatan": "Takkalalla", "code": "73.13.03.2009", "areaHa": 17.52411816559983, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 4}]},
    "tanasitolo::ujungbaru": {"name": "Ujungbaru", "kecamatan": "Tanasitolo", "code": "73.13.08.2018", "areaHa": 1.5258977680747587, "status": "Batas Indikatif", "layers": [{"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}, {"layerId": "potensi-peternakan", "label": "Potensi Peternakan", "count": 1}]},
    "sabangparu::salotengnga": {"name": "Salotengnga", "kecamatan": "Sabangparu", "code": "73.13.01.2009", "areaHa": 4.042389750648487, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 5}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 4}]},
    "pitumpanua::buriko": {"name": "Buriko", "kecamatan": "Pitumpanua", "code": "73.13.10.2017", "areaHa": 3.228808800968303, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 2}]},
    "tanasitolo::pajalele": {"name": "Pajalele", "kecamatan": "Tanasitolo", "code": "73.13.08.2014", "areaHa": 2.368845181711496, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 1}]},
    "gilireng::polewalie": {"name": "Polewalie", "kecamatan": "Gilireng", "code": "73.13.13.2008", "areaHa": 4.231941587737439, "status": "Batas Indikatif", "layers": [{"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 1}]},
    "penrang::raddae": {"name": "Raddae", "kecamatan": "Penrang", "code": "73.13.12.2010", "areaHa": 8.627555170792371, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 2}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}]},
    "keera::inrello": {"name": "Inrello", "kecamatan": "Keera", "code": "73.13.14.2006", "areaHa": 27.704645616778055, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 6}]},
    "pammana::tonrongtengnga": {"name": "Tonrong Tengnga", "kecamatan": "Pammana", "code": "73.13.02.2016", "areaHa": 4.935171562485428, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 2}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}]},
    "pitumpanua::simpellu": {"name": "Simpellu", "kecamatan": "Pitumpanua", "code": "73.13.10.2013", "areaHa": 6.990485450698483, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}, {"layerId": "potensi-peternakan", "label": "Potensi Peternakan", "count": 1}]},
    "tanasitolo::wewangrewu": {"name": "Wewangrewu", "kecamatan": "Tanasitolo", "code": "73.13.08.2010", "areaHa": 11.99876327566568, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 5}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 2}]},
    "takkalalla::aluppang": {"name": "Aluppang", "kecamatan": "Takkalalla", "code": "73.13.03.2011", "areaHa": 6.990445525263547, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 2}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 1}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}]},
    "pitumpanua::padangloang": {"name": "Padang Loang", "kecamatan": "Pitumpanua", "code": "73.13.10.2026", "areaHa": 6.9236697171283, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 2}]},
    "bola::solo": {"name": "Solo", "kecamatan": "Bola", "code": "73.13.11.1001", "areaHa": 16.387711657388728, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 2}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 5}]},
    "pammana::tobatang": {"name": "Tobatang", "kecamatan": "Pammana", "code": "73.13.02.2014", "areaHa": 11.907857680389201, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 3}]},
    "keera::paojepe": {"name": "Paojepe", "kecamatan": "Keera", "code": "73.13.14.2005", "areaHa": 24.838502056790524, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 4}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 1}]},
    "maniangpajo::tangkoli": {"name": "Tangkoli", "kecamatan": "Maniangpajo", "code": "73.13.09.1003", "areaHa": 12.967506146486153, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 4}, {"layerId": "potensi-peternakan", "label": "Potensi Peternakan", "count": 1}]},
    "majauleng::tellulimpoe": {"name": "Tellulimpoe", "kecamatan": "Majauleng", "code": "73.13.05.2016", "areaHa": 12.040213537552477, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 2}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 3}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 1}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 2}]},
    "tanasitolo::barutancung": {"name": "Barutancung", "kecamatan": "Tanasitolo", "code": "73.13.08.1004", "areaHa": 2.2165494184321823, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 3}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 1}]},
    "pitumpanua::lacinde": {"name": "Lacinde", "kecamatan": "Pitumpanua", "code": "73.13.10.2016", "areaHa": 6.12820623128075, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}]},
    "pitumpanua::mattirowalie": {"name": "Mattiro Walie", "kecamatan": "Pitumpanua", "code": "73.13.10.2023", "areaHa": 6.877553743327146, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 2}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 2}]},
    "majauleng::macanang": {"name": "Macanang", "kecamatan": "Majauleng", "code": "73.13.05.1003", "areaHa": 24.762438246818043, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 2}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 3}]},
    "maniangpajo::sogi": {"name": "Sogi", "kecamatan": "Maniangpajo", "code": "73.13.09.2006", "areaHa": 32.19206478577049, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 6}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 2}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 1}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 2}]},
    "tanasitolo::nepo": {"name": "Nepo", "kecamatan": "Tanasitolo", "code": "73.13.08.2005", "areaHa": 2.3057627058600407, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 5}]},
    "gilireng::mamminasae": {"name": "Mamminasae", "kecamatan": "Gilireng", "code": "73.13.13.2001", "areaHa": 10.972617828307245, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 2}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 4}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 1}]},
    "keera::lalliseng": {"name": "Lalliseng", "kecamatan": "Keera", "code": "73.13.14.2004", "areaHa": 35.05561709069418, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 6}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 2}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 1}]},
    "gilireng::gilireng": {"name": "Gilireng", "kecamatan": "Gilireng", "code": "73.13.13.1002", "areaHa": 7.889566078177055, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 7}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 2}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 1}]},
    "belawa::leppangeng": {"name": "Leppangeng", "kecamatan": "Belawa", "code": "73.13.07.2005", "areaHa": 38.5060344928033, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 15}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 10}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}]},
    "majauleng::rumpia": {"name": "Rumpia", "kecamatan": "Majauleng", "code": "73.13.05.2007", "areaHa": 5.280742517289831, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 9}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 1}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}]},
    "maniangpajo::dualimpoe": {"name": "Dualimpoe", "kecamatan": "Maniangpajo", "code": "73.13.09.1002", "areaHa": 22.81837185241365, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 5}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 2}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 3}]},
    "bola::manurung": {"name": "Manurung", "kecamatan": "Bola", "code": "73.13.11.2008", "areaHa": 14.400111959400785, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 5}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}]},
    "majauleng::paria": {"name": "Paria", "kecamatan": "Majauleng", "code": "73.13.05.1001", "areaHa": 7.412561451328129, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 7}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 1}]},
    "sabangparu::liu": {"name": "Liu", "kecamatan": "Sabangparu", "code": "73.13.01.2004", "areaHa": 9.846489922397087, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 2}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 2}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 1}]},
    "gilireng::arajang": {"name": "Arajang", "kecamatan": "Gilireng", "code": "73.13.13.2004", "areaHa": 45.259800956102005, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 3}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 3}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 2}]},
    "tanasitolo::ujungnge": {"name": "Ujungnge", "kecamatan": "Tanasitolo", "code": "73.13.08.2013", "areaHa": 6.965316544316088, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 1}, {"layerId": "opd", "label": "Organisasi Perangkat Daerah", "count": 1}]},
    "majauleng::tajo": {"name": "Tajo", "kecamatan": "Majauleng", "code": "73.13.05.2013", "areaHa": 21.462803292843905, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 3}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 3}]},
    "pitumpanua::bulete": {"name": "Bulete", "kecamatan": "Pitumpanua", "code": "73.13.10.1001", "areaHa": 15.936323833662103, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 16}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 2}, {"layerId": "infra-energi", "label": "Sarana Energi", "count": 1}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 2}]},
    "tempe::paddupa": {"name": "Paddupa", "kecamatan": "Tempe", "code": "73.13.06.1012", "areaHa": 0.4116531193995307, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 7}, {"layerId": "opd", "label": "Organisasi Perangkat Daerah", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}]},
    "pammana::lempa": {"name": "Lempa", "kecamatan": "Pammana", "code": "73.13.02.2003", "areaHa": 7.286255763924028, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 5}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 1}]},
    "maniangpajo::anabanua": {"name": "Anabanua", "kecamatan": "Maniangpajo", "code": "73.13.09.1001", "areaHa": 10.789292153255765, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 2}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}]},
    "majauleng::lamiku": {"name": "Lamiku", "kecamatan": "Majauleng", "code": "73.13.05.2009", "areaHa": 20.3224007541771, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 3}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 1}]},
    "penrang::penrang": {"name": "Penrang", "kecamatan": "Penrang", "code": "73.13.12.2004", "areaHa": 6.108751571382547, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 3}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}]},
    "pitumpanua::tobarakka": {"name": "Tobarakka", "kecamatan": "Pitumpanua", "code": "73.13.10.1003", "areaHa": 15.266544633200994, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 6}]},
    "bola::sanresengade": {"name": "Sanreseng Ade", "kecamatan": "Bola", "code": "73.13.11.2005", "areaHa": 12.895093662187554, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 4}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 1}]},
    "pammana::cina": {"name": "Cina", "kecamatan": "Pammana", "code": "73.13.02.1002", "areaHa": 18.53903567173406, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 3}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 3}]},
    "pammana::watampanua": {"name": "Watampanua", "kecamatan": "Pammana", "code": "73.13.02.2011", "areaHa": 6.563688268186585, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 3}]},
    "tanasitolo::mannagae": {"name": "Mannagae", "kecamatan": "Tanasitolo", "code": "73.13.08.2019", "areaHa": 14.510146427240832, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 1}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 3}]},
    "pitumpanua::abbanderangnge": {"name": "Abbanderangnge", "kecamatan": "Pitumpanua", "code": "73.13.10.2012", "areaHa": 6.170560991200984, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 3}]},
    "sabangparu::wage": {"name": "Wage", "kecamatan": "Sabangparu", "code": "73.13.01.2007", "areaHa": 7.831958955958123, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 5}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}]},
    "tempe::siengkang": {"name": "Siengkang", "kecamatan": "Tempe", "code": "73.13.06.1001", "areaHa": 0.44685700327350186, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 6}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 1}, {"layerId": "opd", "label": "Organisasi Perangkat Daerah", "count": 5}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 2}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 4}]},
    "takkalalla::pantaitimur": {"name": "Pantai Timur", "kecamatan": "Takkalalla", "code": "73.13.03.2013", "areaHa": 27.0907588945802, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 2}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}]},
    "pitumpanua::kaluku": {"name": "Kaluku", "kecamatan": "Pitumpanua", "code": "73.13.10.2022", "areaHa": 2.567416249984719, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 1}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 2}]},
    "tanasitolo::pakkana": {"name": "Pakkana", "kecamatan": "Tanasitolo", "code": "73.13.08.2008", "areaHa": 3.2969275083179674, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 7}]},
    "tanasitolo::mappadaelo": {"name": "Mappadaelo", "kecamatan": "Tanasitolo", "code": "73.13.08.1002", "areaHa": 6.0670985513215845, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 4}]},
    "pitumpanua::marannu": {"name": "Marannu", "kecamatan": "Pitumpanua", "code": "73.13.10.2011", "areaHa": 4.40581378220619, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 5}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 2}]},
    "maniangpajo::mattirowalie": {"name": "Mattirowalie", "kecamatan": "Maniangpajo", "code": "73.13.09.2004", "areaHa": 16.927428250568326, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 14}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 1}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 3}]},
    "pammana::lagosi": {"name": "Lagosi", "kecamatan": "Pammana", "code": "73.13.02.2007", "areaHa": 7.419773628816298, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 3}]},
    "belawa::ongkoe": {"name": "Ongkoe", "kecamatan": "Belawa", "code": "73.13.07.2004", "areaHa": 21.629028816295836, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 12}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 6}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 3}]},
    "takkalalla::lagoari": {"name": "Lagoari", "kecamatan": "Takkalalla", "code": "73.13.03.2010", "areaHa": 8.23307244383253, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 3}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 2}, {"layerId": "potensi-peternakan", "label": "Potensi Peternakan", "count": 1}]},
    "takkalalla::ajuraja": {"name": "Ajuraja", "kecamatan": "Takkalalla", "code": "73.13.03.2008", "areaHa": 13.171522076779391, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 2}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 3}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 1}]},
    "penrang::lawesso": {"name": "Lawesso", "kecamatan": "Penrang", "code": "73.13.12.2005", "areaHa": 15.730747052861995, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 1}]},
    "keera::labawang": {"name": "Labawang", "kecamatan": "Keera", "code": "73.13.14.2010", "areaHa": 8.08533986806505, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 1}]},
    "majauleng::cinnongtabi": {"name": "Cinnong Tabi", "kecamatan": "Majauleng", "code": "73.13.05.2006", "areaHa": 17.46964196869671, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 5}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}]},
    "bola::rajamawellang": {"name": "Rajamawellang", "kecamatan": "Bola", "code": "73.13.11.2011", "areaHa": 12.828921496160941, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 3}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}]},
    "tempe::wiringpalenae": {"name": "Wiring Palenae", "kecamatan": "Tempe", "code": "73.13.06.1013", "areaHa": 4.000525299305326, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 4}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}]},
    "sabangparu::sompe": {"name": "Sompe", "kecamatan": "Sabangparu", "code": "73.13.01.1003", "areaHa": 8.195793056946622, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 6}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 1}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 2}]},
    "sajoanging::minangae": {"name": "Minangae", "kecamatan": "Sajoanging", "code": "73.13.04.1003", "areaHa": 9.74814107151136, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 3}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}]},
    "pammana::tadangpalie": {"name": "Tadangpalie", "kecamatan": "Pammana", "code": "73.13.02.2012", "areaHa": 13.343566604896303, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 7}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}]},
    "gilireng::abbatireng": {"name": "Abbatireng", "kecamatan": "Gilireng", "code": "73.13.13.2009", "areaHa": 4.731587542638491, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 3}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 2}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 1}]},
    "sabangparu::ujungpero": {"name": "Ujungpero", "kecamatan": "Sabangparu", "code": "73.13.01.2006", "areaHa": 18.267795337377954, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 3}]},
    "tempe::attakkae": {"name": "Attakkae", "kecamatan": "Tempe", "code": "73.13.06.1014", "areaHa": 5.06472880055793, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 7}]},
    "sajoanging::akkotengeng": {"name": "Akkotengeng", "kecamatan": "Sajoanging", "code": "73.13.04.2004", "areaHa": 17.406884869592844, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 5}]},
    "penrang::makmur": {"name": "Makmur", "kecamatan": "Penrang", "code": "73.13.12.2008", "areaHa": 7.003285765268422, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 2}]},
    "pitumpanua::tellesang": {"name": "Tellesang", "kecamatan": "Pitumpanua", "code": "73.13.10.2009", "areaHa": 1.8051742457733748, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 3}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}]},
    "bola::pasirputih": {"name": "Pasir Putih", "kecamatan": "Bola", "code": "73.13.11.2010", "areaHa": 9.291305391961505, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 2}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 3}]},
    "keera::pattirolokka": {"name": "Pattirolokka", "kecamatan": "Keera", "code": "73.13.14.2007", "areaHa": 19.670478636796048, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 3}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}, {"layerId": "infra-energi", "label": "Sarana Energi", "count": 1}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 1}]},
    "belawa::macero": {"name": "Macero", "kecamatan": "Belawa", "code": "73.13.07.1001", "areaHa": 9.768607694706695, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 7}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 6}]},
    "pitumpanua::tangkoro": {"name": "Tangkoro", "kecamatan": "Pitumpanua", "code": "73.13.10.2010", "areaHa": 7.253106340277331, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 2}]},
    "takkalalla::parigi": {"name": "Parigi", "kecamatan": "Takkalalla", "code": "73.13.03.2003", "areaHa": 8.94651748515792, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 3}]},
    "tempe::maddukelleng": {"name": "Maddukelleng", "kecamatan": "Tempe", "code": "73.13.06.1004", "areaHa": 2.3678315060907873, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 10}, {"layerId": "opd", "label": "Organisasi Perangkat Daerah", "count": 2}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 1}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 1}]},
    "bola::pattangngae": {"name": "Pattangngae", "kecamatan": "Bola", "code": "73.13.11.2006", "areaHa": 15.670744902254976, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 5}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 1}]},
    "keera::awo": {"name": "Awo", "kecamatan": "Keera", "code": "73.13.14.2008", "areaHa": 59.62548269721036, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 3}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 4}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 1}]},
    "takkalalla::peneki": {"name": "Peneki", "kecamatan": "Takkalalla", "code": "73.13.03.1001", "areaHa": 11.08556368756387, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 8}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 3}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 2}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 2}]},
    "pammana::lapaukke": {"name": "Lapaukke", "kecamatan": "Pammana", "code": "73.13.02.2006", "areaHa": 13.524092333488925, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 3}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 2}]},
    "pammana::pallawarukka": {"name": "Pallawarukka", "kecamatan": "Pammana", "code": "73.13.02.2008", "areaHa": 3.7067929658994982, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 4}]},
    "majauleng::tua": {"name": "Tua", "kecamatan": "Majauleng", "code": "73.13.05.2012", "areaHa": 13.609026013980221, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 4}]},
    "sabangparu::pallimae": {"name": "Pallimae", "kecamatan": "Sabangparu", "code": "73.13.01.2010", "areaHa": 13.975969073874884, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 5}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 2}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 1}]},
    "maniangpajo::minagatellue": {"name": "Minagatellue", "kecamatan": "Maniangpajo", "code": "73.13.09.2008", "areaHa": 34.699332109654286, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 2}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 1}]},
    "pammana::patila": {"name": "Patila", "kecamatan": "Pammana", "code": "73.13.02.2004", "areaHa": 8.894712761368114, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 7}, {"layerId": "puskesmas", "label": "Puskesmas", "count": 1}, {"layerId": "infra-energi", "label": "Sarana Energi", "count": 4}]},
    "sabangparu::tolotenreng": {"name": "Tolotenreng", "kecamatan": "Sabangparu", "code": "73.13.01.1002", "areaHa": 17.302767825611504, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 8}, {"layerId": "infra-telekomunikasi", "label": "Sarana Telekomunikasi", "count": 1}, {"layerId": "infra-sumber-daya-air", "label": "Sarana Sumber Daya Air", "count": 3}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 4}]},
    "keera::keera": {"name": "Keera", "kecamatan": "Keera", "code": "73.13.14.2003", "areaHa": 14.599841962333882, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 3}]},
    "penrang::tadangpalie": {"name": "Tadangpalie", "kecamatan": "Penrang", "code": "73.13.12.2009", "areaHa": 15.227815975822692, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 1}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 1}]},
    "pitumpanua::kompong": {"name": "Kompong", "kecamatan": "Pitumpanua", "code": "73.13.10.2027", "areaHa": 2.6915846136304236, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 2}]},
    "tempe::tempe": {"name": "Tempe", "kecamatan": "Tempe", "code": "73.13.06.1003", "areaHa": 3.299761539782875, "status": "Batas Indikatif", "layers": [{"layerId": "satuan-pendidikan", "label": "Satuan Pendidikan", "count": 8}, {"layerId": "opd", "label": "Organisasi Perangkat Daerah", "count": 8}, {"layerId": "infra-transportasi", "label": "Sarana Transportasi", "count": 2}, {"layerId": "infra-prasarana-lainnya", "label": "Sarana Prasarana Lainnya", "count": 1}]},
  },
};

export function getAdministrativeType(layerId) {
  if (layerId === "adm-kabupaten") return "kabupaten";
  if (layerId === "adm-kecamatan") return "kecamatan";
  if (layerId === "adm-desa") return "desa";
  return null;
}

function keyPart(value) {
  return String(value ?? "").trim().toLowerCase().replace(/[^a-z0-9]+/g, "");
}

export function getAdministrativeStats(layer, feature) {
  const type = getAdministrativeType(layer?.id);
  if (!type) return null;
  const p = feature?.properties ?? {};
  const kecamatan = String(p.Kecamatan ?? p.WADMKC ?? p.nama_kecamatan ?? "").trim();
  const desa = String(p.Desa ?? p.WADMKD ?? p.nama_desa ?? "").trim();
  const name = type === "kabupaten" ? String(p.nama_kabupaten ?? p.WADMKK ?? p.NAMOBJ ?? "Wajo").trim() : type === "kecamatan" ? kecamatan : desa;
  const keys = new Set();
  keys.add(type === "desa" ? `${keyPart(kecamatan)}::${keyPart(desa)}` : keyPart(name));

  if (type === "kecamatan") {
    const master = getWajoKecamatanByKemendagri(p.kode_kecamatan_kemendagri ?? p.kode_kemendagri ?? p.kode_kecamatan);
    if (master) {
      keys.add(keyPart(master.nameKemendagri));
      keys.add(keyPart(master.nameBps));
    }
  }

  if (type === "desa") {
    const master = getWajoVillageByKemendagriCode(
      p.kode_desa ?? p.kode_kemendagri,
      p.nama_desa_kemendagri ?? p.nama_kemendagri ?? p.Desa ?? p.WADMKD,
    );
    if (master) {
      keys.add(`${keyPart(master.kecamatan.nameKemendagri)}::${keyPart(master.nameBps)}`);
      if (master.nameKemendagri) keys.add(`${keyPart(master.kecamatan.nameKemendagri)}::${keyPart(master.nameKemendagri)}`);
      keys.add(`${keyPart(master.kecamatan.nameBps)}::${keyPart(master.nameBps)}`);
    }
  }

  for (const key of keys) {
    const hit = ADMIN_STATS[type]?.[key];
    if (hit) return hit;
  }
  return null;
}
